apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbfilter
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbfilter/veilarbfilter:{{version}}
  port: 8080
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvveilarbfilter
        mountPath: /var/run/secrets/nais.io/service_user
  liveness:
    path: /veilarbfilter/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /veilarbfilter/internal/isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 1500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  ingresses:
    - https://veilarbfilter.nais.adeo.no
    - https://app.adeo.no/veilarbfilter
  webproxy: true
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /veilarbfilter/internal/metrics
  envFrom:
    - configmap: pto-config
  env:
    - name: JAVA_OPTS
      value: "-XX:MaxRAMPercentage=65.0"
    - name: ISSO_JWKS_URL
      value: https://isso.adeo.no/isso/oauth2/connect/jwk_uri
    - name: ISSO_ISSUER
      value: https://isso.adeo.no:443/isso/oauth2
    - name: VEILARBFILTER_DB_URL
      value: jdbc:postgresql://A01DBVL010.adeo.no:5432/veilarbfilter
    - name: VAULT_MOUNT_PATH
      value: /postgresql/prod-fss
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://abac-veilarb.intern.nav.no/application/asm-pdp/authorize
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    - name: AZUREAD_JWKS_URL
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/discovery/v2.0/keys
