apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbfilter
  namespace: default
  cluster: prod-fss
  labels:
    branch: dev
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbfilter/veilarbfilter:{{version}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  port: 8080
  ingresses:
    - https://veilarbfilter.nais.adeo
    - https://app.adeo.no/veilarbfilter
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvveilarbfilter
        mountPath: /var/run/secrets/nais.io/service_user
  healthcheck:
    liveness:
      path: veilarbfilter/internal/isAlive
      initialDelay: 60
      timeout: 10
    readiness:
      path: veilarbfilter/internal/isReady
      initialDelay: 60
      timeout: 10
  prometheus:
    enabled: true
    path: veilarbfilter/internal/metrics
  resources:
    limits:
      cpu: "6"
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi
  env:
    - name: ISSO_JWKS_URL
      value: https://isso.adeo.no/isso/oauth2/connect/jwk_uri
    - name: ISSO_ISSUER
      value: https://isso.adeo.no:443/isso/oauth2
    - name: VEILARBFILTER_DB_URL
      value: jdbc:postgresql://A01DBVL010.adeo.no:5432/veilarbfilter
    - name: VAULT_MOUNT_PATH
      value: /postgresql/prod-fss
    - name: VEILARBVEILEDERAPI_URL
      value: https://veilarbveileder.nais.adeo.no/veilarbveileder/api
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://wasapp.adeo.no/asm-pdp/authorize
