apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbfilter
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbfilter/veilarbfilter:{{version}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  port: 8080
  ingresses:
    - https://veilarbfilter-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarbfilter
    - https://app-q1.dev.adeo.no/veilarbfilter
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvveilarbfilter
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarbfilter/q1
        mountPath: /var/run/secrets/nais.io/vault
  healthcheck:
    liveness:
      path: veilarbfilter/internal/liveness
      initialDelay: 60
      timeout: 10
    readiness:
      path: veilarbfilter/internal/readiness
      initialDelay: 60
      timeout: 10
  prometheus:
    enabled: false
    path: veilarbfilter/internal/metrics
  resources:
    limits:
      cpu: "1"
      memory: 600Mi
    requests:
      cpu: 500m
      memory: 128Mi
  leaderElection: true
  envFrom:
    - configmap: pto-config
  env:
    - name: JAVA_OPTS
      value: "-Xms4098m -Xmx8096m --illegal-access=permit --add-opens=java.base/java.lang=ALL-UNNAMED"
    - name: ABAC_MODIA_URL
      value: https://abac-modia-q1.dev.intern.nav.no/application/asm-pdp/authorize
