apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbfilter
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbfilter/veilarbfilter:{{version}}
  port: 8080
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvveilarbfilter
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarbfilter/default
        mountPath: /var/run/secrets/nais.io/vault
  liveness:
    path: /veilarbfilter/internal/health/liveness
    initialDelay: 60
    timeout: 10
  readiness:
    path: /veilarbfilter/internal/health/readiness
    initialDelay: 60
    timeout: 10
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: prod-gcp
  resources:
    limits:
      cpu: 1500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  ingresses:
    - https://veilarbfilter.prod-fss-pub.nais.io
    - https://veilarbfilter.intern.nav.no
  webproxy: true
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /veilarbfilter/internal/prometheus
  leaderElection: true
  envFrom:
    - configmap: pto-config
  env:
    - name: VEILARBFILTER_DB_URL
      value: jdbc:postgresql://A01DBVL010.adeo.no:5432/veilarbfilter
    - name: POAO_TILGANG_URL
      value: https://poao-tilgang.intern.nav.no
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
