apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbfilter
  namespace: default
  cluster: prod-fss
  labels:
    team: pto
    branch: master
spec:
  image: docker.pkg.github.com/navikt/veilarbfilter/veilarbfilter:{{version}}
  port: 8080
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvveilarbfilter
        mountPath: /var/run/secrets/nais.io/service_user
  liveness:
    path: /veilarbfilter/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /veilarbfilter/internal/isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://veilarbfilter.nais.adeo.no
    - https://app.adeo.no/veilarbfilter
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /veilarbfilter/metrics
  env:
    - name: ISSO_JWKS_URL
      value: https://isso.adeo.no/isso/oauth2/connect/jwk_uri
    - name: ISSO_ISSUER
      value: https://isso.adeo.no:443/isso/oauth2
    - name: VEILARBFILTER_DB_URL
      value: jdbc:postgresql://A01DBVL010.adeo.no:5432/veilarbfilter
    - name: VAULT_MOUNT_PATH
      value: /postgresql/prod-fss
    - name: VEILARBVEILEDERAPI_URL
      value: https://veilarbveileder.nais.adeo.no/veilarbveileder/api
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://wasapp.adeo.no/asm-pdp/authorize