apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbfilter
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbfilter/veilarbfilter:{{version}}
  port: 8080
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvveilarbfilter
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarbfilter/default
        mountPath: /var/run/secrets/nais.io/vault
  liveness:
    path: /veilarbfilter/internal/isAlive
    initialDelay: 60
    timeout: 10
  readiness:
    path: /veilarbfilter/internal/isReady
    initialDelay: 60
    timeout: 10
  resources:
    limits:
      cpu: 1500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  ingresses:
    - https://veilarbfilter.nais.adeo.no
    - https://app.adeo.no/veilarbfilter
  webproxy: true
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /veilarbfilter/internal/metrics
  leaderElection: true
  envFrom:
    - configmap: pto-config
  env:
    - name: JAVA_OPTS
      value: "-Xms4096m -Xmx10144m --add-opens=java.base/java.lang=ALL-UNNAMED"
    - name: ABAC_MODIA_URL
      value: https://abac-modia.intern.nav.no/application/asm-pdp/authorize
