spring:
  sql:
    init:
      encoding: UTF-8
  datasource:
    embedded-database-connection: none
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    validate-on-migrate: true
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true