apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: veilarbfilter
  namespace: obo
  labels:
    team: obo
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: team-obo
  secretName: veilarbfilter-unleash-api-token
  environment: production
