CREATE TABLE EnhetFilter (
    FILTER_ID SERIAL,
    ENHET_ID VARCHAR (32),
    FILTER_NAVN VARCHAR (255),
    VALGTE_FILTER TEXT,
    PRIMARY KEY (FILTER_ID)
);


CREATE TABLE MinOversiktFilter (
    FILTER_ID SERIAL,
    ENHET_ID VARCHAR (32),
    FILTER_NAVN VARCHAR (255),
    VALGTE_FILTER TEXT,
    PRIMARY KEY (FILTER_ID)
);