CREATE TABLE Filter (
    FILTER_ID SERIAL,
    FILTER_NAVN VARCHAR (255),
    VALGTE_FILTER JSONB,
    OPPRETTET TIMESTAMP,
    PRIMARY KEY (FILTER_ID)
);

ALTER TABLE EnhetFilter DROP CONSTRAINT EnhetFilter_pkey;

INSERT INTO Filter (FILTER_ID, FILTER_NAVN, VALGTE_FILTER, OPPRETTET)
SELECT FILTER_ID, FILTER_NAVN, VALGTE_FILTER, OPPRETTET
FROM EnhetFilter;

ALTER TABLE EnhetFilter RENAME COLUMN FILTER_ID TO VEILEDERGRUPPE_FILTER_ID;

ALTER TABLE EnhetFilter
    ADD CONSTRAINT fk_ENHET_FILTER_ID
    FOREIGN KEY (VEILEDERGRUPPE_FILTER_ID)
    REFERENCES Filter (FILTER_ID);

ALTER TABLE EnhetFilter DROP COLUMN OPPRETTET, DROP COLUMN VALGTE_FILTER, DROP COLUMN FILTER_NAVN;

ALTER TABLE EnhetFilter RENAME TO VeilederGrupperFilter;