CREATE TABLE Filter (
    FILTER_ID SERIAL,
    FILTER_NAVN VARCHAR (255),
    VALGTE_FILTER JSONB,
    OPPRETTET TIMESTAMP,
    PRIMARY KEY (FILTER_ID)
);

ALTER TABLE EnhetFilter DROP CONSTRAINT EnhetFilter_pkey;

ALTER TABLE EnhetFilter ADD COLUMN ENHET_FILTER_ID;

ALTER TABLE EnhetFilter
    ADD CONSTRAINT fk_ENHET_FILTER_ID
    FOREIGN KEY (ENHET_FILTER_ID)
    REFERENCES Filter (FILTER_ID)


INSERT INTO Filter (FILTER_ID, FILTER_NAVN, VALGTE_FILTER, OPPRETTET)
SELECT FILTER_ID, FILTER_NAVN, VALGTE_FILTER, OPPRETTET
FROM EnhetFilter


ALTER TABLE EnhetFilter DROP COLUMN OPPRETTET, DROP COLUMN VALGTE_FILTER, DROP COLUMN FILTER_NAVN;


ALTER TABLE table_name EnhetFilter TO VeilederGrupperFilter;