name: Deploy til Dev
on:
  workflow_dispatch:
env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ghcr.io/${{ github.repository }}/veilarbfilter
  PRINT_PAYLOAD: true
permissions: 
  packages: write
  contents: write
jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build maven artifacts
        run: mvn -B package -D skipTests

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: obo
          build_args: --pull

  deploy-dev:
    name: Deploy application to dev
    needs: build-and-push
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/application/application-config-dev.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}
